version: '3.9'
services:
  backend:
    build: ./
    ports:
      - 3001:3001
    container_name: mongodb_application
    working_dir: /app-backend
    command: dev
    # depends_on:
    #   db:
    #     condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 3001 || exit 1"]
    #   interval: 10s
    #   retries: 5
    volumes:
      - .:/app-backend
  db:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    # healthcheck:
    #   test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    #   timeout: 10s
    #   retries: 5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
networks:
  mongo-network:
    driver: bridge
